### ISSUE TITLE
mb_fetch incorrect bounds for mbgrid

### ISSUE THREAD

**Issue by camante** [ciresdem/geomods#1]
@matth-love 
Screenshot of the issue: 

![mb_fetch_incorrect_bounds](https://user-images.githubusercontent.com/43042351/45648547-1e356580-ba86-11e8-8391-cacd116cb48c.PNG)

**Comment by matth-love** [comment]
Looks like you're using an old version of mbfetch. The most up-to-date version is called 'mbfetch.py' rather than mb_fetch.py. I'd remove the old one from your system as it's no longer being supported. The new one should be installed along with the rest of the fetch programs.

**Comment by camante** [comment]
Ah, thanks!
