### ISSUE TITLE
dcfetch.py not fetching rasters

### ISSUE THREAD

**Issue by camante** [ciresdem/geomods#2]
@matth-love 
dcfetch works with lidar, but when I try to download a raster dataset that falls within my study area shp, it churns, temporarily creates the 0tileindex.shp, but doesn't actually download the data. The datasets are listed with using the -x option and definitely fall within the study area shp.

**Comment by matth-love** [comment]
could you provide me with one of the raster datasets its not downloading; just the id is fine.

**Comment by matth-love** [comment]
Ok, got it fixed. The raster datasets on digital coast are unfortunately not as standardized as the lidar; most of the raster datasets have shapefiles of the raster tiles in a zip and loose, but not all, and some are named different; but it seems like they all have the 0tileindex.zip file; which is now what dcfetch uses for rasters. It works for all the datasets listed; this should work for all rasters now.

**Comment by camante** [comment]
Thanks, Matt!

I get an error when trying to install the updated package. 
It appears to originate in the autoreconf -vif step.

configure.ac:100: error: required file 'python/gmrtfetch/Makefile.in' not found
python/Makefile.am:6: error: required directory python/gmrtfetch does not exist
autoreconf: automake failed with exit status: 1

Is this something that you changed during the update?

**Comment by matth-love** [comment]
Just some missing files...should be good now.

**Comment by camante** [comment]
Cool, thanks!
